apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fb-base-adapter-{{ .Values.environmentName }}
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "fb-base-adapter-{{ .Values.environmentName }}-formbuilder-base-adapter-{{ .Values.environmentName }}-blue"
    external-dns.alpha.kubernetes.io/aws-weight: "0"
spec:
  tls:
    - hosts:
        - formbuilder-base-adapter-{{ .Values.environmentName }}.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: formbuilder-base-adapter-{{ .Values.environmentName }}.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: formbuilder-base-adapter
          servicePort: 4567
