apiVersion: v1
kind: Service
metadata:
  name: fb-base-adapter-{{ .Values.environmentName }}
  namespace: formbuilder-base-adapter-{{ .Values.environmentName }}
  labels:
    app: fb-base-adapter-{{ .Values.environmentName }}
    appGroup: formbuilder-base-adapter
spec:
  ports:
  - port: 4567
    name: http
    targetPort: 4567
  selector:
    app: fb-base-adapter-{{ .Values.environmentName }}
