version: '3.4'

services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: 'test'
        BUNDLE_FLAGS: '--jobs 4 --no-cache'
    environment:
      ENCRYPTION_KEY: '1234567890123456'
    ports:
      - '4567:3000'
