version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@4.0.0 # use v4 of this orb

jobs:
  login-to-aws:
    docker: &docker_image
      - image: 'cimg/ruby:3.1.3-node'
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME # this will use the env var
          region: $ECR_REGION # this will use the env var
      - run: &ecr_login
          name: Login to ecr
          command: |
            aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
            aws configure export-credentials --format env
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  tests:
    working_directory: ~/circle
    docker:
      - image: cimg/ruby:2.7.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: make build
      - run:
          name: test
          command: make test
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: main
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-base-adapter
    docker: &ecr_image
      - image: docker.io/ministryofjustice/fb-builder:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: &workspace_envs
          command: |
            cat bash.env >> $BASH_ENV
      - add_ssh_keys:
          fingerprints:
            - "df:d0:db:5c:80:f6:29:7d:71:c2:cf:96:51:94:aa:82"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_ed25519_dfd0db5c80f6297d71c2cf965194aa82" >> $BASH_ENV
      - run: &deploy_scripts
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to test environment in new cluster
          environment:
            APPLICATION_NAME: fb-base-adapter
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-base-adapter-test
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status: *slack_status
  acceptance_tests:
    docker: *ecr_image
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run: *deploy_scripts
      - run:
          name: Run acceptance tests
          command: './deploy-scripts/bin/acceptance_tests'
      - slack/status:
          only_for_branches: main
          success_message: ":rocket:  Successfully deployed to Test  :guitar:"
          failure_message: ":facepalm:  Acceptance tests failed  :homer-disappear:"
          include_job_number_field: false

workflows:
  version: 2
  release:
    jobs:
      - login-to-aws:
          context: &moj-forms-context
            - moj-forms
      - tests:
          requires:
            - login-to-aws
      - build_and_deploy_to_test:
          context: *moj-forms-context
          requires:
            - tests
          filters:
            branches:
              only:
                - main
      - acceptance_tests:
          context: *moj-forms-context
          requires:
            - build_and_deploy_to_test
          filters:
            branches:
              only:
                - main
