version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  tests:
    working_directory: ~/circle
    docker:
      - image: circleci/buildpack-deps:14.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: make build
      - run:
          name: test
          command: make test
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: master
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-base-adapter
    docker: &ecr_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key:  $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "10:76:81:db:22:4d:03:9a:33:e8:3b:64:a7:34:0c:e2"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_107681db224d039a33e83b64a7340ce2" >> $BASH_ENV
      - run: &deploy_scripts
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to test environment
          environment:
            APPLICATION_NAME: fb-base-adapter
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-base-adapter-test
          command: './deploy-scripts/bin/deploy'
      - run:
          name: deploy to test environment in new cluster
          environment:
            APPLICATION_NAME: fb-base-adapter
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-base-adapter-test
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status: *slack_status
  acceptance_tests:
    docker: *ecr_image
    resource_class: large
    steps:
      - setup_remote_docker
      - run: *deploy_scripts
      - run:
          name: Run acceptance tests
          command: './deploy-scripts/bin/acceptance_tests'
      - slack/status:
          only_for_branches: master
          success_message: ":rocket:  Successfully deployed to Test  :guitar:"
          failure_message: ":facepalm:  Acceptance tests failed  :homer-disappear:"
          include_job_number_field: false

workflows:
  version: 2
  release:
    jobs:
      - tests
      - build_and_deploy_to_test:
          requires:
            - tests
          filters:
            branches:
              only:
                - master
                - deploy-to-test
      - acceptance_tests:
          requires:
            - build_and_deploy_to_test
          filters:
            branches:
              only: master
