version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: circleci/buildpack-deps:14.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: make build
      - run:
          name: test
          command: make test
  deploy_test:
    working_directory: ~/circle/git/fb-base-adapter
    docker: &ecr_base_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - 'f4:ae:38:63:c0:71:e1:18:ef:44:22:29:3c:00:5a:3a'
      - run:
          name: deploy to test environment
          command: './deploy/scripts/circle_deploy.sh $CIRCLE_SHA1 test $KUBE_TOKEN_TEST'

workflows:
  version: 2
  release:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          name: push_app_image
          dockerfile: Dockerfile
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: 'formbuilder/fb-base-adapter'
          tag: "APP_${CIRCLE_SHA1}"
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - deploy-to-test
      - deploy_test:
          requires:
            - push_app_image
            - test
          filters:
            branches:
              only:
                - master
                - deploy-to-test
